// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	BlacklistRefreshToken(ctx context.Context, token string) error
	BlacklistToken(ctx context.Context, token string) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (TokenSvcRefreshToken, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (TokenSvcToken, error)
	DeleteRefreshToken(ctx context.Context, id int64) error
	DeleteToken(ctx context.Context, id int64) error
	GetRefreshTokenByID(ctx context.Context, id int64) (TokenSvcRefreshToken, error)
	GetRefreshTokenByValue(ctx context.Context, token string) (TokenSvcRefreshToken, error)
	GetRevokedRefreshTokens(ctx context.Context, arg GetRevokedRefreshTokensParams) ([]TokenSvcRefreshToken, error)
	GetRevokedTokens(ctx context.Context, arg GetRevokedTokensParams) ([]TokenSvcToken, error)
	GetTokenByID(ctx context.Context, id int64) (TokenSvcToken, error)
	GetTokenByValue(ctx context.Context, token string) (TokenSvcToken, error)
	ListRefreshTokens(ctx context.Context, arg ListRefreshTokensParams) ([]TokenSvcRefreshToken, error)
	ListTokens(ctx context.Context, arg ListTokensParams) ([]TokenSvcToken, error)
	RevokeRefreshToken(ctx context.Context, id int64) error
	RevokeToken(ctx context.Context, id int64) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (UpdateRefreshTokenRow, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) (UpdateTokenRow, error)
	VerifyRefreshToken(ctx context.Context, token string) (TokenSvcRefreshToken, error)
	VerifyToken(ctx context.Context, token string) (TokenSvcToken, error)
}

var _ Querier = (*Queries)(nil)
