// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: refresh_token.sql

package db

import (
	"context"
	"time"
)

const blacklistRefreshToken = `-- name: BlacklistRefreshToken :exec
UPDATE "token_svc"."RefreshTokens" SET revoked = true WHERE token = $1
`

func (q *Queries) BlacklistRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, blacklistRefreshToken, token)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO "token_svc"."RefreshTokens" (
    user_id,
    token,
    expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, token, revoked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (TokenSvcRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i TokenSvcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM "token_svc"."RefreshTokens" WHERE id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, id)
	return err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, user_id, token, revoked, expires_at, created_at FROM "token_svc"."RefreshTokens" WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id int64) (TokenSvcRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i TokenSvcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByValue = `-- name: GetRefreshTokenByValue :one
SELECT id, user_id, token, revoked, expires_at, created_at FROM "token_svc"."RefreshTokens" WHERE token = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByValue(ctx context.Context, token string) (TokenSvcRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByValue, token)
	var i TokenSvcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRevokedRefreshTokens = `-- name: GetRevokedRefreshTokens :many
SELECT id, user_id, token, revoked, expires_at, created_at
FROM "token_svc"."RefreshTokens"
WHERE revoked = true ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetRevokedRefreshTokensParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRevokedRefreshTokens(ctx context.Context, arg GetRevokedRefreshTokensParams) ([]TokenSvcRefreshToken, error) {
	rows, err := q.db.Query(ctx, getRevokedRefreshTokens, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenSvcRefreshToken{}
	for rows.Next() {
		var i TokenSvcRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Revoked,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefreshTokens = `-- name: ListRefreshTokens :many
SELECT id, user_id, token, revoked, expires_at, created_at FROM "token_svc"."RefreshTokens" ORDER BY id LIMIT $1 OFFSET $2
`

type ListRefreshTokensParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRefreshTokens(ctx context.Context, arg ListRefreshTokensParams) ([]TokenSvcRefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokens, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenSvcRefreshToken{}
	for rows.Next() {
		var i TokenSvcRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Revoked,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE "token_svc"."RefreshTokens" SET revoked = true WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :one
UPDATE "token_svc"."RefreshTokens" 
SET 
    user_id = COALESCE($2, user_id),
    token = COALESCE($3, token),
    expires_at = COALESCE($4, expires_at)
WHERE id = $1 RETURNING token, expires_at
`

type UpdateRefreshTokenParams struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

type UpdateRefreshTokenRow struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (UpdateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, updateRefreshToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i UpdateRefreshTokenRow
	err := row.Scan(&i.Token, &i.ExpiresAt)
	return i, err
}

const verifyRefreshToken = `-- name: VerifyRefreshToken :one
SELECT id, user_id, token, revoked, expires_at, created_at FROM "token_svc"."RefreshTokens"
WHERE token = $1 AND revoked = false AND expires_at > NOW() LIMIT 1
`

func (q *Queries) VerifyRefreshToken(ctx context.Context, token string) (TokenSvcRefreshToken, error) {
	row := q.db.QueryRow(ctx, verifyRefreshToken, token)
	var i TokenSvcRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
