// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: refresh_token/rpc_revoke_refresh_token.proto

package refresh_token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevokeRefreshTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RevokeRefreshTokenRequest) Reset() {
	*x = RevokeRefreshTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refresh_token_rpc_revoke_refresh_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRefreshTokenRequest) ProtoMessage() {}

func (x *RevokeRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refresh_token_rpc_revoke_refresh_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_refresh_token_rpc_revoke_refresh_token_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeRefreshTokenRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_refresh_token_rpc_revoke_refresh_token_proto protoreflect.FileDescriptor

var file_refresh_token_rpc_revoke_refresh_token_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f,
	0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x42,
	0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x66, 0x61, 0x69, 0x72, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x66,
	0x61, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x70, 0x5f, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x72,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_refresh_token_rpc_revoke_refresh_token_proto_rawDescOnce sync.Once
	file_refresh_token_rpc_revoke_refresh_token_proto_rawDescData = file_refresh_token_rpc_revoke_refresh_token_proto_rawDesc
)

func file_refresh_token_rpc_revoke_refresh_token_proto_rawDescGZIP() []byte {
	file_refresh_token_rpc_revoke_refresh_token_proto_rawDescOnce.Do(func() {
		file_refresh_token_rpc_revoke_refresh_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_refresh_token_rpc_revoke_refresh_token_proto_rawDescData)
	})
	return file_refresh_token_rpc_revoke_refresh_token_proto_rawDescData
}

var file_refresh_token_rpc_revoke_refresh_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_refresh_token_rpc_revoke_refresh_token_proto_goTypes = []interface{}{
	(*RevokeRefreshTokenRequest)(nil), // 0: pb.RevokeRefreshTokenRequest
}
var file_refresh_token_rpc_revoke_refresh_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_refresh_token_rpc_revoke_refresh_token_proto_init() }
func file_refresh_token_rpc_revoke_refresh_token_proto_init() {
	if File_refresh_token_rpc_revoke_refresh_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_refresh_token_rpc_revoke_refresh_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeRefreshTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_refresh_token_rpc_revoke_refresh_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_refresh_token_rpc_revoke_refresh_token_proto_goTypes,
		DependencyIndexes: file_refresh_token_rpc_revoke_refresh_token_proto_depIdxs,
		MessageInfos:      file_refresh_token_rpc_revoke_refresh_token_proto_msgTypes,
	}.Build()
	File_refresh_token_rpc_revoke_refresh_token_proto = out.File
	file_refresh_token_rpc_revoke_refresh_token_proto_rawDesc = nil
	file_refresh_token_rpc_revoke_refresh_token_proto_goTypes = nil
	file_refresh_token_rpc_revoke_refresh_token_proto_depIdxs = nil
}
