// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: refresh_token/rpc_get_refresh_token_by_id.proto

package refresh_token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRefreshTokenByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRefreshTokenByIdRequest) Reset() {
	*x = GetRefreshTokenByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRefreshTokenByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefreshTokenByIdRequest) ProtoMessage() {}

func (x *GetRefreshTokenByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefreshTokenByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRefreshTokenByIdRequest) Descriptor() ([]byte, []int) {
	return file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetRefreshTokenByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRefreshTokenByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken *RefreshToken `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *GetRefreshTokenByIdResponse) Reset() {
	*x = GetRefreshTokenByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRefreshTokenByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefreshTokenByIdResponse) ProtoMessage() {}

func (x *GetRefreshTokenByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefreshTokenByIdResponse.ProtoReflect.Descriptor instead.
func (*GetRefreshTokenByIdResponse) Descriptor() ([]byte, []int) {
	return file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetRefreshTokenByIdResponse) GetRefreshToken() *RefreshToken {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

var File_refresh_token_rpc_get_refresh_token_by_id_proto protoreflect.FileDescriptor

var file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f,
	0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x21, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x54, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x0c,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x3d, 0x5a, 0x3b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x66, 0x61, 0x69, 0x72, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x66, 0x61, 0x69, 0x72,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescOnce sync.Once
	file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescData = file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDesc
)

func file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescGZIP() []byte {
	file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescOnce.Do(func() {
		file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescData)
	})
	return file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDescData
}

var file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_refresh_token_rpc_get_refresh_token_by_id_proto_goTypes = []interface{}{
	(*GetRefreshTokenByIdRequest)(nil),  // 0: pb.GetRefreshTokenByIdRequest
	(*GetRefreshTokenByIdResponse)(nil), // 1: pb.GetRefreshTokenByIdResponse
	(*RefreshToken)(nil),                // 2: pb.RefreshToken
}
var file_refresh_token_rpc_get_refresh_token_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetRefreshTokenByIdResponse.refresh_token:type_name -> pb.RefreshToken
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_refresh_token_rpc_get_refresh_token_by_id_proto_init() }
func file_refresh_token_rpc_get_refresh_token_by_id_proto_init() {
	if File_refresh_token_rpc_get_refresh_token_by_id_proto != nil {
		return
	}
	file_refresh_token_refresh_token_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRefreshTokenByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRefreshTokenByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_refresh_token_rpc_get_refresh_token_by_id_proto_goTypes,
		DependencyIndexes: file_refresh_token_rpc_get_refresh_token_by_id_proto_depIdxs,
		MessageInfos:      file_refresh_token_rpc_get_refresh_token_by_id_proto_msgTypes,
	}.Build()
	File_refresh_token_rpc_get_refresh_token_by_id_proto = out.File
	file_refresh_token_rpc_get_refresh_token_by_id_proto_rawDesc = nil
	file_refresh_token_rpc_get_refresh_token_by_id_proto_goTypes = nil
	file_refresh_token_rpc_get_refresh_token_by_id_proto_depIdxs = nil
}
