// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: idp_svc.proto

package pb

import (
	context "context"
	refresh_token "github.com/Streamfair/streamfair_token_svc/pb/refresh_token"
	token "github.com/Streamfair/streamfair_token_svc/pb/token"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IdentityProvider_BlacklistToken_FullMethodName          = "/pb.IdentityProvider/BlacklistToken"
	IdentityProvider_CreateToken_FullMethodName             = "/pb.IdentityProvider/CreateToken"
	IdentityProvider_DeleteToken_FullMethodName             = "/pb.IdentityProvider/DeleteToken"
	IdentityProvider_GetRevokedTokens_FullMethodName        = "/pb.IdentityProvider/GetRevokedTokens"
	IdentityProvider_GetTokenByID_FullMethodName            = "/pb.IdentityProvider/GetTokenByID"
	IdentityProvider_GetTokenByValue_FullMethodName         = "/pb.IdentityProvider/GetTokenByValue"
	IdentityProvider_ListTokens_FullMethodName              = "/pb.IdentityProvider/ListTokens"
	IdentityProvider_RevokeToken_FullMethodName             = "/pb.IdentityProvider/RevokeToken"
	IdentityProvider_UpdateToken_FullMethodName             = "/pb.IdentityProvider/UpdateToken"
	IdentityProvider_VerifyToken_FullMethodName             = "/pb.IdentityProvider/VerifyToken"
	IdentityProvider_BlacklistRefreshToken_FullMethodName   = "/pb.IdentityProvider/BlacklistRefreshToken"
	IdentityProvider_CreateRefreshToken_FullMethodName      = "/pb.IdentityProvider/CreateRefreshToken"
	IdentityProvider_DeleteRefreshToken_FullMethodName      = "/pb.IdentityProvider/DeleteRefreshToken"
	IdentityProvider_GetRefreshTokenByID_FullMethodName     = "/pb.IdentityProvider/GetRefreshTokenByID"
	IdentityProvider_GetRefreshTokenByValue_FullMethodName  = "/pb.IdentityProvider/GetRefreshTokenByValue"
	IdentityProvider_GetRevokedRefreshTokens_FullMethodName = "/pb.IdentityProvider/GetRevokedRefreshTokens"
	IdentityProvider_ListRefreshTokens_FullMethodName       = "/pb.IdentityProvider/ListRefreshTokens"
	IdentityProvider_RevokeRefreshToken_FullMethodName      = "/pb.IdentityProvider/RevokeRefreshToken"
	IdentityProvider_UpdateRefreshToken_FullMethodName      = "/pb.IdentityProvider/UpdateRefreshToken"
	IdentityProvider_VerifyRefreshToken_FullMethodName      = "/pb.IdentityProvider/VerifyRefreshToken"
)

// IdentityProviderClient is the client API for IdentityProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityProviderClient interface {
	// Tokens
	BlacklistToken(ctx context.Context, in *token.BlacklistTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateToken(ctx context.Context, in *token.CreateTokenRequest, opts ...grpc.CallOption) (*token.CreateTokenResponse, error)
	DeleteToken(ctx context.Context, in *token.DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetRevokedTokens(ctx context.Context, in *token.GetRevokedTokensRequest, opts ...grpc.CallOption) (*token.GetRevokedTokensResponse, error)
	GetTokenByID(ctx context.Context, in *token.GetTokenByIDRequest, opts ...grpc.CallOption) (*token.GetTokenByIDResponse, error)
	GetTokenByValue(ctx context.Context, in *token.GetTokenByValueRequest, opts ...grpc.CallOption) (*token.GetTokenByValueResponse, error)
	ListTokens(ctx context.Context, in *token.ListTokensRequest, opts ...grpc.CallOption) (*token.ListTokensResponse, error)
	RevokeToken(ctx context.Context, in *token.RevokeTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateToken(ctx context.Context, in *token.UpdateTokenRequest, opts ...grpc.CallOption) (*token.UpdateTokenResponse, error)
	VerifyToken(ctx context.Context, in *token.VerifyTokenRequest, opts ...grpc.CallOption) (*token.VerifyTokenResponse, error)
	// Refresh tokens
	BlacklistRefreshToken(ctx context.Context, in *refresh_token.BlacklistRefreshTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateRefreshToken(ctx context.Context, in *refresh_token.CreateRefreshTokenRequest, opts ...grpc.CallOption) (*refresh_token.CreateRefreshTokenResponse, error)
	DeleteRefreshToken(ctx context.Context, in *refresh_token.DeleteRefreshTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetRefreshTokenByID(ctx context.Context, in *refresh_token.GetRefreshTokenByIDRequest, opts ...grpc.CallOption) (*refresh_token.GetRefreshTokenByIDResponse, error)
	GetRefreshTokenByValue(ctx context.Context, in *refresh_token.GetRefreshTokenByValueRequest, opts ...grpc.CallOption) (*refresh_token.GetRefreshTokenByValueResponse, error)
	GetRevokedRefreshTokens(ctx context.Context, in *refresh_token.GetRevokedRefreshTokensRequest, opts ...grpc.CallOption) (*refresh_token.GetRevokedRefreshTokensResponse, error)
	ListRefreshTokens(ctx context.Context, in *refresh_token.ListRefreshTokensRequest, opts ...grpc.CallOption) (*refresh_token.ListRefreshTokensResponse, error)
	RevokeRefreshToken(ctx context.Context, in *refresh_token.RevokeRefreshTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateRefreshToken(ctx context.Context, in *refresh_token.UpdateRefreshTokenRequest, opts ...grpc.CallOption) (*refresh_token.UpdateRefreshTokenResponse, error)
	VerifyRefreshToken(ctx context.Context, in *refresh_token.VerifyRefreshTokenRequest, opts ...grpc.CallOption) (*refresh_token.VerifyRefreshTokenResponse, error)
}

type identityProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityProviderClient(cc grpc.ClientConnInterface) IdentityProviderClient {
	return &identityProviderClient{cc}
}

func (c *identityProviderClient) BlacklistToken(ctx context.Context, in *token.BlacklistTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IdentityProvider_BlacklistToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) CreateToken(ctx context.Context, in *token.CreateTokenRequest, opts ...grpc.CallOption) (*token.CreateTokenResponse, error) {
	out := new(token.CreateTokenResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_CreateToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) DeleteToken(ctx context.Context, in *token.DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IdentityProvider_DeleteToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) GetRevokedTokens(ctx context.Context, in *token.GetRevokedTokensRequest, opts ...grpc.CallOption) (*token.GetRevokedTokensResponse, error) {
	out := new(token.GetRevokedTokensResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_GetRevokedTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) GetTokenByID(ctx context.Context, in *token.GetTokenByIDRequest, opts ...grpc.CallOption) (*token.GetTokenByIDResponse, error) {
	out := new(token.GetTokenByIDResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_GetTokenByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) GetTokenByValue(ctx context.Context, in *token.GetTokenByValueRequest, opts ...grpc.CallOption) (*token.GetTokenByValueResponse, error) {
	out := new(token.GetTokenByValueResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_GetTokenByValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) ListTokens(ctx context.Context, in *token.ListTokensRequest, opts ...grpc.CallOption) (*token.ListTokensResponse, error) {
	out := new(token.ListTokensResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_ListTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) RevokeToken(ctx context.Context, in *token.RevokeTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IdentityProvider_RevokeToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) UpdateToken(ctx context.Context, in *token.UpdateTokenRequest, opts ...grpc.CallOption) (*token.UpdateTokenResponse, error) {
	out := new(token.UpdateTokenResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_UpdateToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) VerifyToken(ctx context.Context, in *token.VerifyTokenRequest, opts ...grpc.CallOption) (*token.VerifyTokenResponse, error) {
	out := new(token.VerifyTokenResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_VerifyToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) BlacklistRefreshToken(ctx context.Context, in *refresh_token.BlacklistRefreshTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IdentityProvider_BlacklistRefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) CreateRefreshToken(ctx context.Context, in *refresh_token.CreateRefreshTokenRequest, opts ...grpc.CallOption) (*refresh_token.CreateRefreshTokenResponse, error) {
	out := new(refresh_token.CreateRefreshTokenResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_CreateRefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) DeleteRefreshToken(ctx context.Context, in *refresh_token.DeleteRefreshTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IdentityProvider_DeleteRefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) GetRefreshTokenByID(ctx context.Context, in *refresh_token.GetRefreshTokenByIDRequest, opts ...grpc.CallOption) (*refresh_token.GetRefreshTokenByIDResponse, error) {
	out := new(refresh_token.GetRefreshTokenByIDResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_GetRefreshTokenByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) GetRefreshTokenByValue(ctx context.Context, in *refresh_token.GetRefreshTokenByValueRequest, opts ...grpc.CallOption) (*refresh_token.GetRefreshTokenByValueResponse, error) {
	out := new(refresh_token.GetRefreshTokenByValueResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_GetRefreshTokenByValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) GetRevokedRefreshTokens(ctx context.Context, in *refresh_token.GetRevokedRefreshTokensRequest, opts ...grpc.CallOption) (*refresh_token.GetRevokedRefreshTokensResponse, error) {
	out := new(refresh_token.GetRevokedRefreshTokensResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_GetRevokedRefreshTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) ListRefreshTokens(ctx context.Context, in *refresh_token.ListRefreshTokensRequest, opts ...grpc.CallOption) (*refresh_token.ListRefreshTokensResponse, error) {
	out := new(refresh_token.ListRefreshTokensResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_ListRefreshTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) RevokeRefreshToken(ctx context.Context, in *refresh_token.RevokeRefreshTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IdentityProvider_RevokeRefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) UpdateRefreshToken(ctx context.Context, in *refresh_token.UpdateRefreshTokenRequest, opts ...grpc.CallOption) (*refresh_token.UpdateRefreshTokenResponse, error) {
	out := new(refresh_token.UpdateRefreshTokenResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_UpdateRefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderClient) VerifyRefreshToken(ctx context.Context, in *refresh_token.VerifyRefreshTokenRequest, opts ...grpc.CallOption) (*refresh_token.VerifyRefreshTokenResponse, error) {
	out := new(refresh_token.VerifyRefreshTokenResponse)
	err := c.cc.Invoke(ctx, IdentityProvider_VerifyRefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityProviderServer is the server API for IdentityProvider service.
// All implementations must embed UnimplementedIdentityProviderServer
// for forward compatibility
type IdentityProviderServer interface {
	// Tokens
	BlacklistToken(context.Context, *token.BlacklistTokenRequest) (*emptypb.Empty, error)
	CreateToken(context.Context, *token.CreateTokenRequest) (*token.CreateTokenResponse, error)
	DeleteToken(context.Context, *token.DeleteTokenRequest) (*emptypb.Empty, error)
	GetRevokedTokens(context.Context, *token.GetRevokedTokensRequest) (*token.GetRevokedTokensResponse, error)
	GetTokenByID(context.Context, *token.GetTokenByIDRequest) (*token.GetTokenByIDResponse, error)
	GetTokenByValue(context.Context, *token.GetTokenByValueRequest) (*token.GetTokenByValueResponse, error)
	ListTokens(context.Context, *token.ListTokensRequest) (*token.ListTokensResponse, error)
	RevokeToken(context.Context, *token.RevokeTokenRequest) (*emptypb.Empty, error)
	UpdateToken(context.Context, *token.UpdateTokenRequest) (*token.UpdateTokenResponse, error)
	VerifyToken(context.Context, *token.VerifyTokenRequest) (*token.VerifyTokenResponse, error)
	// Refresh tokens
	BlacklistRefreshToken(context.Context, *refresh_token.BlacklistRefreshTokenRequest) (*emptypb.Empty, error)
	CreateRefreshToken(context.Context, *refresh_token.CreateRefreshTokenRequest) (*refresh_token.CreateRefreshTokenResponse, error)
	DeleteRefreshToken(context.Context, *refresh_token.DeleteRefreshTokenRequest) (*emptypb.Empty, error)
	GetRefreshTokenByID(context.Context, *refresh_token.GetRefreshTokenByIDRequest) (*refresh_token.GetRefreshTokenByIDResponse, error)
	GetRefreshTokenByValue(context.Context, *refresh_token.GetRefreshTokenByValueRequest) (*refresh_token.GetRefreshTokenByValueResponse, error)
	GetRevokedRefreshTokens(context.Context, *refresh_token.GetRevokedRefreshTokensRequest) (*refresh_token.GetRevokedRefreshTokensResponse, error)
	ListRefreshTokens(context.Context, *refresh_token.ListRefreshTokensRequest) (*refresh_token.ListRefreshTokensResponse, error)
	RevokeRefreshToken(context.Context, *refresh_token.RevokeRefreshTokenRequest) (*emptypb.Empty, error)
	UpdateRefreshToken(context.Context, *refresh_token.UpdateRefreshTokenRequest) (*refresh_token.UpdateRefreshTokenResponse, error)
	VerifyRefreshToken(context.Context, *refresh_token.VerifyRefreshTokenRequest) (*refresh_token.VerifyRefreshTokenResponse, error)
	mustEmbedUnimplementedIdentityProviderServer()
}

// UnimplementedIdentityProviderServer must be embedded to have forward compatible implementations.
type UnimplementedIdentityProviderServer struct {
}

func (UnimplementedIdentityProviderServer) BlacklistToken(context.Context, *token.BlacklistTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlacklistToken not implemented")
}
func (UnimplementedIdentityProviderServer) CreateToken(context.Context, *token.CreateTokenRequest) (*token.CreateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (UnimplementedIdentityProviderServer) DeleteToken(context.Context, *token.DeleteTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteToken not implemented")
}
func (UnimplementedIdentityProviderServer) GetRevokedTokens(context.Context, *token.GetRevokedTokensRequest) (*token.GetRevokedTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevokedTokens not implemented")
}
func (UnimplementedIdentityProviderServer) GetTokenByID(context.Context, *token.GetTokenByIDRequest) (*token.GetTokenByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenByID not implemented")
}
func (UnimplementedIdentityProviderServer) GetTokenByValue(context.Context, *token.GetTokenByValueRequest) (*token.GetTokenByValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenByValue not implemented")
}
func (UnimplementedIdentityProviderServer) ListTokens(context.Context, *token.ListTokensRequest) (*token.ListTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTokens not implemented")
}
func (UnimplementedIdentityProviderServer) RevokeToken(context.Context, *token.RevokeTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedIdentityProviderServer) UpdateToken(context.Context, *token.UpdateTokenRequest) (*token.UpdateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateToken not implemented")
}
func (UnimplementedIdentityProviderServer) VerifyToken(context.Context, *token.VerifyTokenRequest) (*token.VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedIdentityProviderServer) BlacklistRefreshToken(context.Context, *refresh_token.BlacklistRefreshTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlacklistRefreshToken not implemented")
}
func (UnimplementedIdentityProviderServer) CreateRefreshToken(context.Context, *refresh_token.CreateRefreshTokenRequest) (*refresh_token.CreateRefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRefreshToken not implemented")
}
func (UnimplementedIdentityProviderServer) DeleteRefreshToken(context.Context, *refresh_token.DeleteRefreshTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRefreshToken not implemented")
}
func (UnimplementedIdentityProviderServer) GetRefreshTokenByID(context.Context, *refresh_token.GetRefreshTokenByIDRequest) (*refresh_token.GetRefreshTokenByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRefreshTokenByID not implemented")
}
func (UnimplementedIdentityProviderServer) GetRefreshTokenByValue(context.Context, *refresh_token.GetRefreshTokenByValueRequest) (*refresh_token.GetRefreshTokenByValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRefreshTokenByValue not implemented")
}
func (UnimplementedIdentityProviderServer) GetRevokedRefreshTokens(context.Context, *refresh_token.GetRevokedRefreshTokensRequest) (*refresh_token.GetRevokedRefreshTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevokedRefreshTokens not implemented")
}
func (UnimplementedIdentityProviderServer) ListRefreshTokens(context.Context, *refresh_token.ListRefreshTokensRequest) (*refresh_token.ListRefreshTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRefreshTokens not implemented")
}
func (UnimplementedIdentityProviderServer) RevokeRefreshToken(context.Context, *refresh_token.RevokeRefreshTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeRefreshToken not implemented")
}
func (UnimplementedIdentityProviderServer) UpdateRefreshToken(context.Context, *refresh_token.UpdateRefreshTokenRequest) (*refresh_token.UpdateRefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRefreshToken not implemented")
}
func (UnimplementedIdentityProviderServer) VerifyRefreshToken(context.Context, *refresh_token.VerifyRefreshTokenRequest) (*refresh_token.VerifyRefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyRefreshToken not implemented")
}
func (UnimplementedIdentityProviderServer) mustEmbedUnimplementedIdentityProviderServer() {}

// UnsafeIdentityProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityProviderServer will
// result in compilation errors.
type UnsafeIdentityProviderServer interface {
	mustEmbedUnimplementedIdentityProviderServer()
}

func RegisterIdentityProviderServer(s grpc.ServiceRegistrar, srv IdentityProviderServer) {
	s.RegisterService(&IdentityProvider_ServiceDesc, srv)
}

func _IdentityProvider_BlacklistToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.BlacklistTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).BlacklistToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_BlacklistToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).BlacklistToken(ctx, req.(*token.BlacklistTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.CreateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_CreateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).CreateToken(ctx, req.(*token.CreateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.DeleteTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).DeleteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_DeleteToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).DeleteToken(ctx, req.(*token.DeleteTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_GetRevokedTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.GetRevokedTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).GetRevokedTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_GetRevokedTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).GetRevokedTokens(ctx, req.(*token.GetRevokedTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_GetTokenByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.GetTokenByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).GetTokenByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_GetTokenByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).GetTokenByID(ctx, req.(*token.GetTokenByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_GetTokenByValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.GetTokenByValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).GetTokenByValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_GetTokenByValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).GetTokenByValue(ctx, req.(*token.GetTokenByValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_ListTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.ListTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).ListTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_ListTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).ListTokens(ctx, req.(*token.ListTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).RevokeToken(ctx, req.(*token.RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_UpdateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.UpdateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).UpdateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_UpdateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).UpdateToken(ctx, req.(*token.UpdateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(token.VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).VerifyToken(ctx, req.(*token.VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_BlacklistRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.BlacklistRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).BlacklistRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_BlacklistRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).BlacklistRefreshToken(ctx, req.(*refresh_token.BlacklistRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_CreateRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.CreateRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).CreateRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_CreateRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).CreateRefreshToken(ctx, req.(*refresh_token.CreateRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_DeleteRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.DeleteRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).DeleteRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_DeleteRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).DeleteRefreshToken(ctx, req.(*refresh_token.DeleteRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_GetRefreshTokenByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.GetRefreshTokenByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).GetRefreshTokenByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_GetRefreshTokenByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).GetRefreshTokenByID(ctx, req.(*refresh_token.GetRefreshTokenByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_GetRefreshTokenByValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.GetRefreshTokenByValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).GetRefreshTokenByValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_GetRefreshTokenByValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).GetRefreshTokenByValue(ctx, req.(*refresh_token.GetRefreshTokenByValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_GetRevokedRefreshTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.GetRevokedRefreshTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).GetRevokedRefreshTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_GetRevokedRefreshTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).GetRevokedRefreshTokens(ctx, req.(*refresh_token.GetRevokedRefreshTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_ListRefreshTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.ListRefreshTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).ListRefreshTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_ListRefreshTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).ListRefreshTokens(ctx, req.(*refresh_token.ListRefreshTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_RevokeRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.RevokeRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).RevokeRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_RevokeRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).RevokeRefreshToken(ctx, req.(*refresh_token.RevokeRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_UpdateRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.UpdateRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).UpdateRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_UpdateRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).UpdateRefreshToken(ctx, req.(*refresh_token.UpdateRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProvider_VerifyRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(refresh_token.VerifyRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderServer).VerifyRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityProvider_VerifyRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderServer).VerifyRefreshToken(ctx, req.(*refresh_token.VerifyRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityProvider_ServiceDesc is the grpc.ServiceDesc for IdentityProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.IdentityProvider",
	HandlerType: (*IdentityProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlacklistToken",
			Handler:    _IdentityProvider_BlacklistToken_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _IdentityProvider_CreateToken_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _IdentityProvider_DeleteToken_Handler,
		},
		{
			MethodName: "GetRevokedTokens",
			Handler:    _IdentityProvider_GetRevokedTokens_Handler,
		},
		{
			MethodName: "GetTokenByID",
			Handler:    _IdentityProvider_GetTokenByID_Handler,
		},
		{
			MethodName: "GetTokenByValue",
			Handler:    _IdentityProvider_GetTokenByValue_Handler,
		},
		{
			MethodName: "ListTokens",
			Handler:    _IdentityProvider_ListTokens_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _IdentityProvider_RevokeToken_Handler,
		},
		{
			MethodName: "UpdateToken",
			Handler:    _IdentityProvider_UpdateToken_Handler,
		},
		{
			MethodName: "VerifyToken",
			Handler:    _IdentityProvider_VerifyToken_Handler,
		},
		{
			MethodName: "BlacklistRefreshToken",
			Handler:    _IdentityProvider_BlacklistRefreshToken_Handler,
		},
		{
			MethodName: "CreateRefreshToken",
			Handler:    _IdentityProvider_CreateRefreshToken_Handler,
		},
		{
			MethodName: "DeleteRefreshToken",
			Handler:    _IdentityProvider_DeleteRefreshToken_Handler,
		},
		{
			MethodName: "GetRefreshTokenByID",
			Handler:    _IdentityProvider_GetRefreshTokenByID_Handler,
		},
		{
			MethodName: "GetRefreshTokenByValue",
			Handler:    _IdentityProvider_GetRefreshTokenByValue_Handler,
		},
		{
			MethodName: "GetRevokedRefreshTokens",
			Handler:    _IdentityProvider_GetRevokedRefreshTokens_Handler,
		},
		{
			MethodName: "ListRefreshTokens",
			Handler:    _IdentityProvider_ListRefreshTokens_Handler,
		},
		{
			MethodName: "RevokeRefreshToken",
			Handler:    _IdentityProvider_RevokeRefreshToken_Handler,
		},
		{
			MethodName: "UpdateRefreshToken",
			Handler:    _IdentityProvider_UpdateRefreshToken_Handler,
		},
		{
			MethodName: "VerifyRefreshToken",
			Handler:    _IdentityProvider_VerifyRefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idp_svc.proto",
}
