// Code generated by MockGen. DO NOT EDIT.
// Source: db/sqlc/store.go
//
// Generated by this command:
//
//	mockgen -source=db/sqlc/store.go -destination=db/mock/store_mock.go
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/Streamfair/streamfair_token_svc/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockStore) CreateRefreshToken(ctx context.Context, arg db.CreateRefreshTokenParams) (db.TokenSvcRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, arg)
	ret0, _ := ret[0].(db.TokenSvcRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockStoreMockRecorder) CreateRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockStore)(nil).CreateRefreshToken), ctx, arg)
}

// CreateToken mocks base method.
func (m *MockStore) CreateToken(ctx context.Context, arg db.CreateTokenParams) (db.TokenSvcToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, arg)
	ret0, _ := ret[0].(db.TokenSvcToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockStoreMockRecorder) CreateToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockStore)(nil).CreateToken), ctx, arg)
}

// DeleteRefreshToken mocks base method.
func (m *MockStore) DeleteRefreshToken(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockStoreMockRecorder) DeleteRefreshToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockStore)(nil).DeleteRefreshToken), ctx, id)
}

// DeleteToken mocks base method.
func (m *MockStore) DeleteToken(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockStoreMockRecorder) DeleteToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockStore)(nil).DeleteToken), ctx, id)
}

// DeleteTokenByValue mocks base method.
func (m *MockStore) DeleteTokenByValue(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTokenByValue", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTokenByValue indicates an expected call of DeleteTokenByValue.
func (mr *MockStoreMockRecorder) DeleteTokenByValue(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTokenByValue", reflect.TypeOf((*MockStore)(nil).DeleteTokenByValue), ctx, token)
}

// GetRefreshTokenByID mocks base method.
func (m *MockStore) GetRefreshTokenByID(ctx context.Context, id int64) (db.TokenSvcRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByID", ctx, id)
	ret0, _ := ret[0].(db.TokenSvcRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByID indicates an expected call of GetRefreshTokenByID.
func (mr *MockStoreMockRecorder) GetRefreshTokenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByID", reflect.TypeOf((*MockStore)(nil).GetRefreshTokenByID), ctx, id)
}

// GetRefreshTokenByValue mocks base method.
func (m *MockStore) GetRefreshTokenByValue(ctx context.Context, token string) (db.TokenSvcRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByValue", ctx, token)
	ret0, _ := ret[0].(db.TokenSvcRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByValue indicates an expected call of GetRefreshTokenByValue.
func (mr *MockStoreMockRecorder) GetRefreshTokenByValue(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByValue", reflect.TypeOf((*MockStore)(nil).GetRefreshTokenByValue), ctx, token)
}

// GetTokenByID mocks base method.
func (m *MockStore) GetTokenByID(ctx context.Context, id int64) (db.TokenSvcToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByID", ctx, id)
	ret0, _ := ret[0].(db.TokenSvcToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByID indicates an expected call of GetTokenByID.
func (mr *MockStoreMockRecorder) GetTokenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByID", reflect.TypeOf((*MockStore)(nil).GetTokenByID), ctx, id)
}

// GetTokenByValue mocks base method.
func (m *MockStore) GetTokenByValue(ctx context.Context, token string) (db.TokenSvcToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByValue", ctx, token)
	ret0, _ := ret[0].(db.TokenSvcToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByValue indicates an expected call of GetTokenByValue.
func (mr *MockStoreMockRecorder) GetTokenByValue(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByValue", reflect.TypeOf((*MockStore)(nil).GetTokenByValue), ctx, token)
}

// ListRefreshTokens mocks base method.
func (m *MockStore) ListRefreshTokens(ctx context.Context, arg db.ListRefreshTokensParams) ([]db.TokenSvcRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRefreshTokens", ctx, arg)
	ret0, _ := ret[0].([]db.TokenSvcRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRefreshTokens indicates an expected call of ListRefreshTokens.
func (mr *MockStoreMockRecorder) ListRefreshTokens(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRefreshTokens", reflect.TypeOf((*MockStore)(nil).ListRefreshTokens), ctx, arg)
}

// ListRevokedRefreshTokens mocks base method.
func (m *MockStore) ListRevokedRefreshTokens(ctx context.Context, arg db.ListRevokedRefreshTokensParams) ([]db.TokenSvcRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRevokedRefreshTokens", ctx, arg)
	ret0, _ := ret[0].([]db.TokenSvcRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRevokedRefreshTokens indicates an expected call of ListRevokedRefreshTokens.
func (mr *MockStoreMockRecorder) ListRevokedRefreshTokens(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRevokedRefreshTokens", reflect.TypeOf((*MockStore)(nil).ListRevokedRefreshTokens), ctx, arg)
}

// ListRevokedTokens mocks base method.
func (m *MockStore) ListRevokedTokens(ctx context.Context, arg db.ListRevokedTokensParams) ([]db.TokenSvcToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRevokedTokens", ctx, arg)
	ret0, _ := ret[0].([]db.TokenSvcToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRevokedTokens indicates an expected call of ListRevokedTokens.
func (mr *MockStoreMockRecorder) ListRevokedTokens(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRevokedTokens", reflect.TypeOf((*MockStore)(nil).ListRevokedTokens), ctx, arg)
}

// ListTokens mocks base method.
func (m *MockStore) ListTokens(ctx context.Context, arg db.ListTokensParams) ([]db.TokenSvcToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", ctx, arg)
	ret0, _ := ret[0].([]db.TokenSvcToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockStoreMockRecorder) ListTokens(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockStore)(nil).ListTokens), ctx, arg)
}

// Ping mocks base method.
func (m *MockStore) Ping(ctx context.Context, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoreMockRecorder) Ping(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStore)(nil).Ping), ctx, timeout)
}

// RevokeRefreshTokenByID mocks base method.
func (m *MockStore) RevokeRefreshTokenByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshTokenByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshTokenByID indicates an expected call of RevokeRefreshTokenByID.
func (mr *MockStoreMockRecorder) RevokeRefreshTokenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshTokenByID", reflect.TypeOf((*MockStore)(nil).RevokeRefreshTokenByID), ctx, id)
}

// RevokeRefreshTokenByValue mocks base method.
func (m *MockStore) RevokeRefreshTokenByValue(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshTokenByValue", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshTokenByValue indicates an expected call of RevokeRefreshTokenByValue.
func (mr *MockStoreMockRecorder) RevokeRefreshTokenByValue(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshTokenByValue", reflect.TypeOf((*MockStore)(nil).RevokeRefreshTokenByValue), ctx, token)
}

// RevokeTokenByID mocks base method.
func (m *MockStore) RevokeTokenByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTokenByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTokenByID indicates an expected call of RevokeTokenByID.
func (mr *MockStoreMockRecorder) RevokeTokenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTokenByID", reflect.TypeOf((*MockStore)(nil).RevokeTokenByID), ctx, id)
}

// RevokeTokenByValue mocks base method.
func (m *MockStore) RevokeTokenByValue(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTokenByValue", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTokenByValue indicates an expected call of RevokeTokenByValue.
func (mr *MockStoreMockRecorder) RevokeTokenByValue(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTokenByValue", reflect.TypeOf((*MockStore)(nil).RevokeTokenByValue), ctx, token)
}

// UpdateRefreshToken mocks base method.
func (m *MockStore) UpdateRefreshToken(ctx context.Context, arg db.UpdateRefreshTokenParams) (db.TokenSvcRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", ctx, arg)
	ret0, _ := ret[0].(db.TokenSvcRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRefreshToken indicates an expected call of UpdateRefreshToken.
func (mr *MockStoreMockRecorder) UpdateRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockStore)(nil).UpdateRefreshToken), ctx, arg)
}

// UpdateToken mocks base method.
func (m *MockStore) UpdateToken(ctx context.Context, arg db.UpdateTokenParams) (db.TokenSvcToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToken", ctx, arg)
	ret0, _ := ret[0].(db.TokenSvcToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateToken indicates an expected call of UpdateToken.
func (mr *MockStoreMockRecorder) UpdateToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToken", reflect.TypeOf((*MockStore)(nil).UpdateToken), ctx, arg)
}

// VerifyRefreshToken mocks base method.
func (m *MockStore) VerifyRefreshToken(ctx context.Context, token string) (db.TokenSvcRefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefreshToken", ctx, token)
	ret0, _ := ret[0].(db.TokenSvcRefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRefreshToken indicates an expected call of VerifyRefreshToken.
func (mr *MockStoreMockRecorder) VerifyRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefreshToken", reflect.TypeOf((*MockStore)(nil).VerifyRefreshToken), ctx, token)
}

// VerifyToken mocks base method.
func (m *MockStore) VerifyToken(ctx context.Context, token string) (db.TokenSvcToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, token)
	ret0, _ := ret[0].(db.TokenSvcToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockStoreMockRecorder) VerifyToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockStore)(nil).VerifyToken), ctx, token)
}
